apiVersion: v1
kind: Service
metadata:
  name: model-{model_id}
  labels:
    app: application-{application_id}
    tier: model
spec:
  selector:
    app: application-{application_id}
  ports:
  - name: model-port
    port: 65327
    targetPort: 65327
