apiVersion: v1
kind: Service
metadata:
  name: prepr_#{preprocessing_id}
  labels:
    app: application_#{application_id}
    tier: preprocessing
spec:
  selector:
    app: application_#{application_id}
  ports:
  - name: prep_port
    port: 8000
    targetPort: 8000
