apiVersion: v1
kind: Service
metadata:
  name: prepr-{preprocessing_id}
  labels:
    app: application-{application_id}
    tier: preprocessing
spec:
  selector:
    app: application-{application_id}
  ports:
  - name: prep-port
    port: 8000
    targetPort: 8000
