apiVersion: v1
kind: Service
metadata:
  name: pyxis-app
  labels:
    app: pyxis
    tier: main
spec:
  selector:
    app: pyxis
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8888
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8888
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pyxis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyxis
      tier: main
  template:
    metadata:
      labels:
        app: pyxis
        tier: main
    spec:
      containers:
      - name: pyxis-app
        image: 998377059405.dkr.ecr.eu-central-1.amazonaws.com/pyxis-app
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_USER
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_PASS
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_PORT
        ports:
        - containerPort: 8888
          hostPort: 8888
