apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka_producer_application_#{application_id}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka_producer_application_#{application_id}
      tier: producer
  template:
    metadata:
      labels:
        app: kafka_producer_application_#{application_id}
        tier: producer
    spec:
      containers:
      - name: kafka_producer_application_#{application_id}
        image: 998377059405.dkr.ecr.eu-central-1.amazonaws.com/pyxis-kafka-producer:latest
        imagePullPolicy: Always
        env:
          - name: TWITTER_API_KEY
            valueFrom:
              configMapKeyRef:
                name: kafka-producer-config
                key: TWITTER_API_KEY
          - name: TWITTER_API_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: kafka-producer-config
                key: TWITTER_API_SECRET_KEY
          - name: TWITTER_ACCESS_TOKEN
            valueFrom:
              configMapKeyRef:
                name: kafka-producer-config
                key: TWITTER_ACCESS_TOKEN
          - name: WORDS_TO_TRACK
            valueFrom:
              configMapKeyRef:
                name: kafka-producer-config
                key: WORDS_TO_TRACK
