apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: server
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: server
  template:
    metadata:
      labels:
        app: mongodb
        tier: server
    spec:
      containers:
      - name: mongodb
        image: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-cluster
          mountPath: /data
      volumes:
      - name: mongo-cluster
        awsElasticBlockStore:
          volumeID: EBS_VOLUME_ID # volume id from aws console.
          fsType: ext4
