apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: server
spec:
  selector:
    app: postgresql
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: server
  template:
    metadata:
      labels:
        app: postgresql
        tier: server
    spec:
      containers:
      - name: postgresql
        image: postgres
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          hostPort: 32769
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
