apiVersion: v1
kind: Service
metadata:
  name: prepr-{preprocessing_id}
  labels:
    app: pipeline-{pipeline_id}
    tier: preprocessing
spec:
  selector:
    app: pipeline-{pipeline_id}
  ports:
  - name: prep-port
    port: 65327
    targetPort: 65327
