apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  labels:
    app: kafka
    tier: server
spec:
  selector:
    app: kafka
  ports:
  - name: kafka-server
    port: 9092
    targetPort: 9092
  - name: kafka-zookeeper
    port: 2181
    targetPort: 2181
