apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dispatcher-{application_id}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-{application_id}
  template:
    metadata:
      labels:
        app: dispatcher-{application_id}
    spec:
      containers:
      - name: dispatcher-{application_id}
        image: 998377059405.dkr.ecr.eu-central-1.amazonaws.com/pyxis-dispatcher:latest
        imagePullPolicy: Always
        env:
          - name: MONGODB_HOST
            valueFrom:
              secretKeyRef:
                name: mongodb_secrets
                key: MONGODB_HOST
          - name: MONGODB_PORT
            valueFrom:
              secretKeyRef:
                name: mongodb_secrets
                key: MONGODB_PORT
          - name: MONGODB_DBNAME
            value: {MONGODB_NAME}
          - name: MONGODB_COLLECTION_NAME
            value: {MONGODB_COLLECTION_NAME}
          - name: KAFKA_TOPIC
            value: {KAFKA_TOPIC}
          - name: KAFKA_BOOTSTRAP_SERVER
            value: kafka-server
